### ISSUE TITLE
The section Orientate is not working and appears as a plain white page 

### ISSUE THREAD

**Issue by MarE1991** [noi-techpark/it.bz.noi.community.android#75] opened 2021-11-17 16:25 UTC
Version: 0.1.0.1637051767
Device used: Asus Zenfone 5
When clicking on the section "Orientate", instead of the interface with maps, a plain white page is shown. 
@Piiit could you check this please and eventually assign to someone from Dimension? THX!

**Comment by Piiit** [comment] 2021-11-17 16:36
@MarE1991 Thx for the report, I need more information thou:

- What does "instead of the interface with maps" mean?
- Could you please try to clear the cache of the application and retry
- Please provide a step-by-step list... I am currently unable to reproduce this issue

I will assign you and myself in the meantime :-)

**Comment by MarE1991** [comment] 2021-11-18 13:35
@Piiit instead of the interface simply means that Elisa can't see the maps, but only sees a white page... She can see the navigation bar and also the title and the "Book a room"-button, but she can't see maps. She already cleared the cache but the problem still exists.

**Comment by Piiit** [comment] 2021-11-23 08:11
@MarE1991 A new version (ending in ...611141) has been released yesterday, please test again and eventually close this issue

**Comment by MarE1991** [comment] 2021-11-23 12:48
> @MarE1991 A new version (ending in ...611141) has been released yesterday, please test again and eventually close this issue

@Piiit she has deleted the app, cleared the cache, reinstalled the latest version, but it is still not working...

**Comment by chiaraDimension** [comment] 2021-11-23 13:05
@Piiit I reproduced the issue with Italian version. Maybe it's a problem with Italian URL, I'll check it.

**Comment by Piiit** [comment] 2021-11-23 13:08
@chiaraDimension That could be, in the past the URL without a language tag inside (like `/it`) was the Italian version... Now we always need to put the corresponding language in the URL... 

--> https://maps.noi.bz.it/it/ or https://maps.noi.bz.it/de/ or https://maps.noi.bz.it/en/

The root address should redirect to the English version (https://maps.noi.bz.it)... could it be that redirection does not work as embedded browser frame?

**Comment by chiaraDimension** [comment] 2021-11-23 15:05
> @chiaraDimension That could be, in the past the URL without a language tag inside (like `/it`) was the Italian version... Now we always need to put the corresponding language in the URL...
> 
> --> https://maps.noi.bz.it/it/ or https://maps.noi.bz.it/de/ or https://maps.noi.bz.it/en/
> 
> The root address should redirect to the English version (https://maps.noi.bz.it)... could it be that redirection does not work as embedded browser frame?

Yes, that's exactly it. I changed the Italian URL from https://maps.noi.bz.it to https://maps.noi.bz.it/it/ and this will fix the issue (see #78).

**Comment by Piiit** [comment] 2021-11-24 15:47
@MarE1991 The newest version (0.1.0.1637740955) should solve this issue, please test again and eventually close the issue

**Closed** 2021-11-24 15:54 UTC
Labels: bug, prj:noiapp
